### PR TITLE
feat: graphql example server

### PR DESCRIPTION
**Pull request by ankithans**
@wtrocki 
I have created a graphQL server. But was not sure about the next steps. 
For now, the server adds, search and get all characters. Can you guide me a little further!

image
image
image

### CODE REVIEW

**Comment by wtrocki** [comment]
Misscommunication - there are already examples in the repository.
See https://github.com/aerogear/graphql-link/tree/master/internal/gateway/examples

**Comment by wtrocki** [comment]
If you ever have doubts or need some extra info feel free to ask :D

**Comment by ankithans** [comment]
oops, got it, I just had to change the endpoints in ```graphql-link.yaml``` file. Is that the case?


> If you ever have doubts or need some extra info feel free to ask :D

Yeah will take care next time 😅. It got me to learn more about Golang though!

**Comment by wtrocki** [comment]
So to be clear. Having graphql example is amazing. but we already have ones so we can move them out and organize along with your new ones. That will be desired state. 

I will not merge change with two example folders in different places.

**Comment by ankithans** [comment]
Okay, got it, doing it rn!

**Comment by ankithans** [comment]
@wtrocki can you check it now?

**Comment by wtrocki** [comment]
Let's have friday break. Will look later.

**Comment by ankithans** [comment]
Yeah sure, no problem 😀

**Comment by wtrocki** [comment]
I'm missing readme/website page that shows how to run test those examples. 
Apart from that looks pristine

**Comment by ankithans** [comment]
okay so, I will add that in documentation (website).

**Comment by wtrocki** [comment]
Thank you. I will use that doc to build verification suite to start servers in GitHub and then make couple graphql requests.

**Comment by wtrocki** [comment]
FYI @chirino

**Comment by ankithans** [comment]
@wtrocki https://ankithans.github.io/graphql-link/docs/run_examples

**Comment by wtrocki** [comment]
My take would be to have examples running at separate process and use CLI in guide with config

**Comment by wtrocki** [comment]
Updated

**Comment by wtrocki** [comment]
Made update

**Comment by ankithans** [comment]
Okay got it, so we are not moving examples outside.

**Comment by wtrocki** [comment]
> Okay got it, so we are not moving examples outside. we are giving them with CLI.

No. we move them outside. 
./examples is separate process to graphql-link CLI process

Actually I will take over from here but really need to have more than 5h of sleep and see it tommorow

**Comment by ankithans** [comment]
yup got it now! 👍

**Comment by wtrocki** [comment]
CLI running example APIs is really bad..

**Comment by ankithans** [comment]
Yeah 😅

**Comment by wtrocki** [comment]
@ankithans Are you still interested in reformating this change?

**Comment by ankithans** [comment]
yeah I am interested
1. for examples we want to provide them compiled in release. Can you guide me how should I approach this?

**Comment by wtrocki** [comment]
> for examples we want to provide them compiled in release. Can you guide me how should I approach this?

Examples can be separate binaries attached to github releases. 
I can do that no problem. Feel free to ignore it for now (let's not do too much in this PR.

**Comment by ankithans** [comment]
@wtrocki now the examples can be run at seperate processes.

**Comment by wtrocki** [comment]
Ok. then more documentation is needed. We just moved those files there, but how people will run them etc.
Docs

**Comment by ankithans** [comment]
yup, on it.

**Comment by ankithans** [comment]
@wtrocki  take a look at docs. https://ankithans.github.io/graphql-link/docs/run_examples

**Review by wtrocki — APPROVED** [review]

**Pull request merged**
