### PR TITLE
fix: add CORS setup

### PR DESCRIPTION
**Pull request by namit-chandwani**
## Changes Made:

I have added a basic CORS setup using the [rs/cors](http://github.com/rs/cors) package.

## Further Comments:

However, to test these changes when containerized, I created a new docker image with the updated code (by executing the `build.sh` script present in the `docker/` directory). 
After running this latest image as a container, I noticed that the initial docker image issue which was pointed out in #39, still exists.

Do I need to make any further changes to the CORS config in order to fix it?

### CODE REVIEW

**Comment by wtrocki** [comment]
I will look into this

**Comment by wtrocki** [comment]
I'm not sure if makes sense to bring framework into this.

@chirino WDYT?

**Comment by chirino** [comment]
I think this is fine and I think overtime more options of the framework may need to be exposed so that admins can control who can connect to the endpoint.

**Comment by wtrocki** [comment]
@chirino thank you so much. Yes. This is just start. I wanted you to approve choice of the framework. If we pick some more top level framework we can now take number of improvements like cors wildcards etc.

**Comment by wtrocki** [comment]
@namit-chandwani Thank you for contribution. Verified. All good

**Pull request merged**
